"""Initial schema

Revision ID: 1312f8e110a8
Revises: 
Create Date: 2025-11-03 19:52:50.705113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1312f8e110a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('parent_email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_email', sa.String(length=255), nullable=False),
    sa.Column('amount_rub', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_chats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('learner_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id')
    )
    op.create_table('progress_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('learner_id', sa.String(), nullable=False),
    sa.Column('reporting_period', sa.String(length=50), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=False),
    sa.Column('focus_areas', sa.Text(), nullable=False),
    sa.Column('milestones', sa.Text(), nullable=False),
    sa.Column('tests_payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progress_reports')
    op.drop_table('parent_chats')
    op.drop_table('subscription_invoices')
    op.drop_table('learners')
    # ### end Alembic commands ###
