"""Add report_history table

Revision ID: 808be0d282b5
Revises: 940ffb8733bd
Create Date: 2025-11-03 21:38:37.939289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808be0d282b5'
down_revision = '940ffb8733bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False, comment='weekly, monthly, on_demand'),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('lessons_completed', sa.Integer(), nullable=False),
    sa.Column('tests_taken', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('days_without_skip', sa.Integer(), nullable=False),
    sa.Column('courses_in_progress', sa.Integer(), nullable=False),
    sa.Column('courses_completed', sa.Integer(), nullable=False),
    sa.Column('ai_recommendations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_history_parent_id'), 'report_history', ['parent_id'], unique=False)
    op.create_index('ix_report_history_parent_sent', 'report_history', ['parent_id', 'sent_at'], unique=False)
    op.create_index('ix_report_history_type_period', 'report_history', ['report_type', 'period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_report_history_type_period', table_name='report_history')
    op.drop_index('ix_report_history_parent_sent', table_name='report_history')
    op.drop_index(op.f('ix_report_history_parent_id'), table_name='report_history')
    op.drop_table('report_history')
    # ### end Alembic commands ###
