"""Add bot models: Parent, ParentStudent, Subscription, Payment, DialogMessage, EventLog, Notification

Revision ID: 940ffb8733bd
Revises: 1312f8e110a8
Create Date: 2025-11-03 20:33:31.902432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940ffb8733bd'
down_revision = '1312f8e110a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parents_telegram_id'), 'parents', ['telegram_id'], unique=True)
    op.create_table('dialog_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='user, assistant, system'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True, comment='Количество токенов'),
    sa.Column('model', sa.String(length=50), nullable=True, comment='gpt-4, gpt-3.5-turbo и т.д.'),
    sa.Column('prompt_version', sa.String(length=50), nullable=True, comment='Версия промпта для A/B тестов'),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialog_messages_parent_id'), 'dialog_messages', ['parent_id'], unique=False)
    op.create_index('ix_dialog_messages_parent_timestamp', 'dialog_messages', ['parent_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_dialog_messages_timestamp'), 'dialog_messages', ['timestamp'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='PARENT_REGISTERED, STUDENT_LINKED, DIALOG_STARTED, PAYMENT_SUCCESS и т.д.'),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('platform_student_id', sa.String(length=255), nullable=True, comment='ID ученика из platform DB'),
    sa.Column('payload', sa.Text(), nullable=True, comment='JSON с деталями события'),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_logs_parent_id'), 'event_logs', ['parent_id'], unique=False)
    op.create_index(op.f('ix_event_logs_timestamp'), 'event_logs', ['timestamp'], unique=False)
    op.create_index('ix_event_logs_type_timestamp', 'event_logs', ['event_type', 'timestamp'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False, comment='TEST_COMPLETED, SUBSCRIPTION_EXPIRING, NEW_COURSE, INACTIVITY_REMINDER'),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_parent_id'), 'notifications', ['parent_id'], unique=False)
    op.create_index('ix_notifications_parent_sent', 'notifications', ['parent_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_notifications_sent_at'), 'notifications', ['sent_at'], unique=False)
    op.create_table('parent_students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('platform_student_id', sa.String(length=255), nullable=False, comment='ID ученика из platform DB'),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Основной ребёнок для этого родителя'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_students_parent_id'), 'parent_students', ['parent_id'], unique=False)
    op.create_index('ix_parent_students_parent_platform', 'parent_students', ['parent_id', 'platform_student_id'], unique=True)
    op.create_index(op.f('ix_parent_students_platform_student_id'), 'parent_students', ['platform_student_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False, comment='ID транзакции от провайдера'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='PAYME, CLICK'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='PENDING, SUCCESS, FAILED, CANCELLED, REFUNDED'),
    sa.Column('external_ref', sa.String(length=255), nullable=True, comment='Дополнительная референс-информация'),
    sa.Column('payment_metadata', sa.Text(), nullable=True, comment='JSON с деталями платежа'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_parent_id'), 'payments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='PENDING, ACTIVE, EXPIRED, CANCELLED'),
    sa.Column('tariff', sa.String(length=50), nullable=False, comment='MONTHLY, YEARLY или другие тарифы'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Сумма в UZS'),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_expires_at'), 'subscriptions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_parent_id'), 'subscriptions', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_parent_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_expires_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_parent_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_parent_students_platform_student_id'), table_name='parent_students')
    op.drop_index('ix_parent_students_parent_platform', table_name='parent_students')
    op.drop_index(op.f('ix_parent_students_parent_id'), table_name='parent_students')
    op.drop_table('parent_students')
    op.drop_index(op.f('ix_notifications_sent_at'), table_name='notifications')
    op.drop_index('ix_notifications_parent_sent', table_name='notifications')
    op.drop_index(op.f('ix_notifications_parent_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_event_logs_type_timestamp', table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_timestamp'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_parent_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_dialog_messages_timestamp'), table_name='dialog_messages')
    op.drop_index('ix_dialog_messages_parent_timestamp', table_name='dialog_messages')
    op.drop_index(op.f('ix_dialog_messages_parent_id'), table_name='dialog_messages')
    op.drop_table('dialog_messages')
    op.drop_index(op.f('ix_parents_telegram_id'), table_name='parents')
    op.drop_table('parents')
    # ### end Alembic commands ###
