"""add_subscription_id_to_payments

Revision ID: 20dbce44fdbf
Revises: 808be0d282b5
Create Date: 2025-11-03 22:01:00.799632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20dbce44fdbf'
down_revision = '808be0d282b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('subscription_id', sa.Integer(), nullable=True, comment='Связь с подпиской'))
    op.alter_column('payments', 'provider',
               existing_type=sa.VARCHAR(length=20),
               comment='PAYME, CLICK, TELEGRAM_STARS',
               existing_comment='PAYME, CLICK',
               existing_nullable=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.alter_column('payments', 'provider',
               existing_type=sa.VARCHAR(length=20),
               comment='PAYME, CLICK',
               existing_comment='PAYME, CLICK, TELEGRAM_STARS',
               existing_nullable=False)
    op.drop_column('payments', 'subscription_id')
    # ### end Alembic commands ###
